export enum FORM_MESSAGE {
  EMAIL_FORMAT = "Por favor digite um e-mail valido!",
  PASSWORD_SIZE = "A senha deve conter no minimo 8 caracteres!",
  CONFIRM_PASSWORD = "As senhas não conferem!",
  NAME = "Digite seu nome!",
  RESUME_TITLE = "O título deve ser informado!",
  RESUME_SUMMARY = "O sumário deve ser informado!",
  EXPERIENCE_COMPANY_NAME = "O nome da empresa deve ser informado!",
  EXPERIENCE_ROLE = "O cargo deve ser informado!",
  EXPERIENCE_START_DATE = "A data de início deve ser informada!",
  EDUCATION_INSTITUTION_NAME = "O nome da instituição deve ser informado!",
  EDUCATION_DEGREE = "O gráu de educação deve ser informado!",
  EDUCATION_START_DATE = "A data de início deve ser informada!",
  SKILL_NAME = "O nome da habilidade deve ser informado!",
  SKILL_LINK = "O link do icone da habilidade deve ser informado!",
  PORTFOLIO_ITEM_NAME = "O nome da item do portfolio deve ser informado!",
  PORTFOLIO_ITEM_DESCRIPTION = "Uma descrição para o item do portfolio deve ser informado!",
  PORTFOLIO_ITEM_TECHNOLOGIES = "Informe pelo menos uma técnologia utilizada. Para multiplas tecnologias, separar por espaço.",
}
